import { PaymentProps } from "../contracts/payment.contract";

export type CreateForSubscriptionProps = Pick<
  PaymentProps,
  | "idempotencyKey"
  | "transactionId"
  | "stripeInvoiceId"
  | "paymentStatus"
  | "paymentGateway"
  | "paymentFor"
  | "slotflowSubscriptionId"
  | "subtotalAmount"
  | "discountAmount"
  | "totalAmount"
  | "currency"
  | "billingCycle"
  | "userId"
  | "stripeCustomerId"
  | "stripeSubscriptionId"
  | "gatewayFee"
  | "receiptUrl"
  | "receiptPdf"
  | "customerEmail"
  | "customerName"
  | "description"
  | "paidAt"
>;

export type CreateForBookingProps = Pick<
  PaymentProps,
  | "idempotencyKey"
  | "transactionId"
  | "stripeInvoiceId"
  | "paymentStatus"
  | "paymentGateway"
  | "paymentFor"
  | "subtotalAmount"
  | "discountAmount"
  | "totalAmount"
  | "currency"
  | "userId"
  | "providerId"
  | "stripeCustomerId"
  | "gatewayFee"
  | "receiptUrl"
  | "receiptPdf"
  | "customerEmail"
  | "customerName"
  | "description"
  | "slotflowBookingId"
  | "paidAt"
>;

export type CreateForPaymentFailedProps = Pick<
  PaymentProps,
  | "idempotencyKey"
  | "transactionId"
  | "stripeInvoiceId"
  | "paymentStatus"
  | "paymentGateway"
  | "paymentFor"
  | "subtotalAmount"
  | "discountAmount"
  | "totalAmount"
  | "currency"
  | "userId"
  | "stripeCustomerId"
  | "gatewayFee"
  | "paymentIntent"
  | "sessionId"
  | "customerEmail"
  | "customerName"
  | "description"
  | "slotflowSubscriptionId"
  | "slotflowBookingId"
>;
export type PaymentRefundedProps = Pick<PaymentProps, "refundedAmount">;
